---
title: "HW 5 R"
author: "Joe Sturino"
date: "October 5, 2015"
output: html_document
---
#Problem 1)

'''{r}

#calling the data frame of diamonds to be used
data(diamonds)
#viewing the components that make up the data frame of diamonds
str(diamonds)

#defined a new vector that uses the method sapply which takes all the parts of the data frame diamonds in this case and pulls out the ones that are numeric in nature
numericCol <- diamonds[sapply(diamonds, is.numeric)]
#str() of the newly defined numericCol vector shows the parts of Diamonds dataframe that actually are  numeric

str(numericCol)
'''

#Problem 2)

'''{r}
data(diamonds)

#in order to find pearsons correlation we need all the numeric columns in a data frame
#so this is the assigning numericCol to be all the columns in diamonds that apply to being numeric

numericCol <- diamonds[sapply(diamonds, is.numeric)]

#begining of manipulating the subsetted data frame numericCol to be read as every pair of variable names in seperated by '-' and then the pearson correlation of each pair of the two original variables
 
#using within() I made a new variable and coresponing vector that uses the paste method to take the numeric values in the variable vectors carat and depth and returns the pearson correlation in the newly created variable and vector within the data frame numericCol

#first is column 1, carat and column 2, depth
#both used to create the new variable and vector 'carat-depth' with corresponding correlations of the original columns in the new one
numericCol <- within(numericCol, "carat-depth" <- paste(cor(carat,depth,method="pearson")))

str(numericCol)
#next change being made to numericCol, is another new variable which combines the next pair of variables with a vector containing the pearson correlation of the original two variable vectors
numericCol <- within(numericCol, "depth-table" <- paste(cor(depth,table,method="pearson")))

#same process used as previous for the next set of pairs
numericCol <- within(numericCol, "table-price" <- paste(cor(table,price,method="pearson")))

#continuing the process to match all the pairs of numeric columns
numericCol <- within(numericCol, "price-x" <- paste(cor(price,x,method="pearson")))

numericCol <- within(numericCol, "x-y" <- paste(cor(x,y,method="pearson")))

numericCol <- within(numericCol, "y-z" <- paste(cor(y,z,method="pearson")))

#after all the new variables are created we look at the str() of the subsetted data frame numericCol 
#All of the previous was put in the data frame as new members of the data frame under the original variables used to create these new ones 
str(numericCol)

#next we want to get rid of the original variable columns so that we only see the new pearson correlation data frame
#next, deleted the vectors out of the data frame by subsetting similar to the way we got all the numeric columns out of the diamonds data
#took the df, numericCol and deleted the numbered vectors NumericCol designated, in this case, all the original variables used to make the new ones

numericCol <- subset(numericCol, select = -c(1,2,3,4,5,6,7))

#str() shows the data frame numericCol, is only the paired variables seperated by '-' and the corresponding vector is the pearson correlation of those original vectors described in the title of the data frame set

str(numericCol)
'''

#Problem 3)

'''{r}
#using the data frame diamonds to conduct this problem
data(diamonds)

#since this problem requires making graphs and ploting points, requireing the packages grid and ggplot2 are needed
require(grid)
require(ggplot2)
#since we are looking to plot points from the data frame diamonds, we can only plot numeric values so, extracting all the numeric variables and corresponding vectors is a good idea
#thats what we did here, and then assigned this new subsetted data frame to numericCol
numericCol <- diamonds[sapply(diamonds, is.numeric)]

#checking to make sure we have the data how we would like it to be (all numeric variables)
str(numericCol)

#next we take each pair of vectors and plot those points, with a title that describes the correlation coefficients found in problem 2
 
#scatterplot of carats to depth, pearson cor. being .0282...
plot(numericCol$carat,numericCol$depth, main = "Pearson Corr.Coeff=.0282", xlab = "Carat", ylab = "Depth")

#scatterplot of depth to table, pearson cor. being -.2957...
plot(numericCol$depth,numericCol$table, main = "Pearson Corr.Coeff=-.2957", xlab = "Depth", ylab = "Table")
 
#scatterplot of table to price, pearson cor. being .1271
plot(numericCol$table,numericCol$price, main = "Pearson Corr.Coeff=.1271", xlab = "Table", ylab = "Price")

#scatterplot of price to variable 'x', pearson cor. being .8844...
plot(numericCol$price,numericCol$x, main = "Pearson Corr.Coeff=.8844", xlab = "Price", ylab = "X")
 
#scatterplot of variable 'x' to variable 'y', pearson cor. being .9747...
plot(numericCol$x,numericCol$y, main = "Pearson Corr.Coeff=.9747", xlab = "X", ylab = "Y")
 
#scatter plot of variable 'y' to variable 'z', pearson cor. being .9520...
plot(numericCol$y,numericCol$z, main = "Pearson Corr.Coeff=.9520", xlab = "X", ylab = "Y")
'''
